name: recipe_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  assorted_layout_widgets: ^10.0.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttericon: ^2.0.0
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  path_provider: ^2.1.5
  cloudinary_sdk: ^5.0.0+1
  image_picker: ^0.8.8+7
  google_sign_in: ^5.4.2
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
