// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43FAC13pu7vsUT6feNJJuYm9MZHPcxcQ',
    appId: '1:252320645083:web:d8f2c0d61b2aa716c5b1fe',
    messagingSenderId: '252320645083',
    projectId: 'recipe-app-bb9c2',
    authDomain: 'recipe-app-bb9c2.firebaseapp.com',
    databaseURL: 'https://recipe-app-bb9c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipe-app-bb9c2.firebasestorage.app',
    measurementId: 'G-Z014QL60C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUN3IEuPtD0QOqGy9jLBjC1Id2OoW0S30',
    appId: '1:252320645083:android:bce37150560b78f3c5b1fe',
    messagingSenderId: '252320645083',
    projectId: 'recipe-app-bb9c2',
    databaseURL: 'https://recipe-app-bb9c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipe-app-bb9c2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA43FAC13pu7vsUT6feNJJuYm9MZHPcxcQ',
    appId: '1:252320645083:web:e5791f9643d3cf50c5b1fe',
    messagingSenderId: '252320645083',
    projectId: 'recipe-app-bb9c2',
    authDomain: 'recipe-app-bb9c2.firebaseapp.com',
    databaseURL: 'https://recipe-app-bb9c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipe-app-bb9c2.firebasestorage.app',
    measurementId: 'G-CS462Y9QPS',
  );
}
